discourse-drbenri:
  drbenri_enabled:
    default: true
    client: true
  auto_play_video:
    default: true
    client: true
  disable_video_controls:
    default: true
    client: true
  default_open_replies:
    default: true
    client: true
